### ISSUE TITLE
Error With Latest (2.3.5)

### ISSUE THREAD

**Issue by greaterweb** [SassDoc/sassdoc-theme-default#77]
I'm getting the following error when using the latest `sassdoc` and `sassdoc-theme-default`

```sh
Error: Cannot find module '6to5-runtime/helpers'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/ronedgecomb/code/wk/bcc/wk.css/node_modules/sassdoc/node_modules/sassdoc-theme-default/dist/swig.js:3:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

Here is a look at the dependencies that were installed.

```sh
sassdoc@2.1.11 node_modules/sassdoc
├── strip-indent@1.0.1 (get-stdin@4.0.1)
├── glob2base@0.0.12 (find-index@0.1.1)
├── docopt@0.6.2
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── vinyl-source-stream@1.1.0 (vinyl@0.4.6)
├── glob@5.0.7 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── safe-wipe@0.2.3 (extend@2.0.1, q@1.4.1)
├── lodash.difference@3.2.1 (lodash.restparam@3.6.1, lodash._baseflatten@3.1.3, lodash._basedifference@3.0.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── rimraf@2.3.4 (glob@4.5.3)
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── lodash.uniq@3.2.0 (lodash._getnative@3.9.0, lodash._isiterateecall@3.0.8, lodash.isarray@3.0.3, lodash._baseuniq@3.0.2, lodash._basecallback@3.3.0)
├── concat-stream@1.4.8 (inherits@2.0.1, typedarray@0.0.6, readable-stream@1.1.13)
├── multipipe@0.1.2 (duplexer2@0.0.2)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, configstore@0.3.2, semver-diff@2.0.0, latest-version@1.0.0)
├── sass-convert@0.5.0 (semver-regex@1.0.0, object-assign@2.0.0, es6-denodeify@0.1.4, dargs@4.0.1, ends-with@0.2.0, which@1.1.1, semver@4.3.4, es6-promise@2.1.1)
├── scss-comment-parser@0.6.0 (cdocparser@0.13.0)
├── sassdoc-theme-default@2.3.5 (es6-denodeify@0.1.4, extend@2.0.1, fs-extra@0.16.5, sassdoc-extras@2.3.0, chroma-js@0.6.3, swig-extras@0.0.1, es6-promise@2.1.1, html-minifier@0.7.2, swig@1.4.0)
├── js-yaml@3.3.1 (esprima@2.2.0, argparse@1.0.2)
├── babel-runtime@5.1.13 (core-js@0.9.11)
└── vinyl-fs@1.0.0 (merge-stream@0.1.7, object-assign@2.0.0, graceful-fs@3.0.7, strip-bom@1.0.0, vinyl@0.4.6, duplexify@3.4.0, glob-watcher@0.0.8, glob-stream@4.1.1)
```

Any help would be greatly appreciated, thanks!

**Comment by HugoGiraudel** [comment]
Could you post your `--debug` please? :)

**Comment by valeriangalliat** [comment]
No need for `--debug`. Looks like the default theme needs 6to5-runtime since the last release but it's not a dependency... probably some ES6 stuff we're using in the theme used to work without runtime but since a new 6to5 version, requires the runtime.

**Comment by valeriangalliat** [comment]
However if I compile the theme now the dist files don't need 6to5-runtime... I'm pblishing a patch.

**Comment by valeriangalliat** [comment]
But WTF, sassdoc-theme-default is still using Babel, so why did it ever require 6to5-runtime? Should be babel-runtime at least. Anyway...

**Comment by valeriangalliat** [comment]
Should be okay with sassdoc-theme-default 2.3.6.

**Comment by greaterweb** [comment]
Seems to be working now, thank you!
